/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quanlykhachhang_quanlytinh;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
